import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,cp,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {cases,assess} from '../site/jev-model.js';
import {jevExplorer,insertJevExplorer} from '../lib/jev-explorer.mjs';
import {build} from '../lib/site.mjs';
import {loadPackage,validatePackage,configAt,fingerprints,hash} from '../lib/content.mjs';
import {rasterInfo} from '../lib/social-image.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),slug='jev-decision-layer';
async function fixture(t){const d=await mkdtemp(path.join(tmpdir(),'jev-publication-'));t.after(()=>rm(d,{recursive:true,force:true}));for(const n of ['articles','lib','site','studio.config.json'])await cp(path.join(root,n),path.join(d,n),{recursive:true});return d;}
async function status(d,id,value){const p=path.join(d,'articles',id,'metadata.json'),m=JSON.parse(await readFile(p,'utf8'));m.status=value;await writeFile(p,JSON.stringify(m));}
test('authored distributions are normalized and never represented as API results',()=>{for(const c of cases){assert.ok(Math.abs(c.probabilities.reduce((a,b)=>a+b,0)-1)<1e-9);}const a=assess();assert.equal(a.route.id,'code');assert.equal(a.status,'checked');assert.match(a.detail,/actually accessed/);});
test('ambiguity requests more evidence instead of forcing the top route',()=>{const a=assess({caseId:'ambiguous'});assert.equal(a.status,'clarify');assert.equal(a.executed,false);});
test('new prose is routed to generation without calling a generative model',()=>assert.equal(assess({caseId:'explanation'}).route.id,'generate'));
test('stale state and denied permission cannot be overruled by the top probability',()=>{assert.equal(assess({fresh:false}).status,'refresh');const b=assess({allowed:false});assert.equal(b.status,'blocked');assert.equal(b.executed,false);assert.equal(b.route.id,'code');});
test('simulated execution without verification is not labeled successful',()=>{const a=assess({verified:false});assert.equal(a.status,'unverified');assert.equal(a.executed,true);assert.throws(()=>assess({caseId:'unknown'}));assert.throws(()=>assess({allowed:'yes'}));});
test('static fallback is useful and inactive, with explicit illustrative limits',()=>{const html=jevExplorer();assert.match(html,/Illustration only/);assert.match(html,/<noscript>/);assert.match(html,/<fieldset class="jev-cases" disabled/);assert.match(html,/not Jev’s confidence/);assert.throws(()=>insertJevExplorer('missing'),/Missing Jev/);});
test('article package has separately labeled social evidence, primary docs, and correct PNG',async()=>{const p=await loadPackage(root,slug);assert.deepEqual(await validatePackage(p,await configAt(root)),[]);assert.equal(p.sources.length,34);assert.equal(p.sources.filter(x=>x.type==='user-supplied-post').length,3);assert.match(p.article,/have not personally benchmarked/);assert.match(p.article,/not evidence of customer-specific online retraining/);const b=await readFile(path.join(p.dir,p.meta.socialImage.path));assert.deepEqual(rasterInfo(b),{type:'image/png',width:1200,height:627});assert.equal(hash(b),'5f5c55c1b54c329c87d1143a47fc3a45d4c72030c00a2af4beb32bcef2594d32');});
test('new publication features Jev while retaining earlier pages and metadata',async t=>{const d=await fixture(t),m=await build(d);assert.equal(m.articles[0].slug,slug);for(const id of [slug,'parallel-agent-engineering','keeping-parallel-development-fast','better-context-for-ai-agents'])assert.ok(m.articles.some(x=>x.slug===id));const h=await readFile(path.join(d,'dist/articles',slug,'index.html'),'utf8');assert.match(h,/id="jev-decision-explorer"/);assert.match(h,/og:image:width" content="1200"/);assert.match(h,/og-image|og-jev-v1.png/);assert.ok(!h.includes('DriftGate'));assert.ok(!h.includes('src="/content/agent-flow.js"'));const home=await readFile(path.join(d,'dist/index.html'),'utf8');assert.ok(!home.includes('src="/content/jev-explorer.js"'));for(const f of ['rss.xml','sitemap.xml'])assert.ok((await readFile(path.join(d,'dist',f),'utf8')).includes('/articles/'+slug+'/'));});
test('Jev article is independently publishable and removal excludes its browser assets',async t=>{const d=await fixture(t);for(const id of await readdir(path.join(d,'articles')))if(id!==slug)await status(d,id,'review');const m=await build(d);assert.deepEqual(m.articles.map(x=>x.slug),[slug]);assert.ok(m.outputs.includes('jev-explorer.js'));assert.ok(!m.outputs.some(p=>p.startsWith('context-')||p.startsWith('devops-')||p.startsWith('vendor/')));await status(d,slug,'review');const next=await build(d);assert.ok(!next.outputs.some(p=>p.includes(slug)||p.startsWith('jev-')));});
test('Jev model edit changes only its own article renderer fingerprint',async t=>{const d=await fixture(t),p=await loadPackage(d,slug),other=await loadPackage(d,'better-context-for-ai-agents'),a=await fingerprints(p,d),b=await fingerprints(other,d),file=path.join(d,'site/jev-model.js');await writeFile(file,(await readFile(file,'utf8'))+'\n// fixture\n');assert.notEqual((await fingerprints(p,d)).renderer,a.renderer);assert.equal((await fingerprints(other,d)).renderer,b.renderer);});
