import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,readFile,writeFile,rm,readdir} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {scenarios,initialState,traceFor,transition,view,canJoin} from '../site/loop-graph-model.js';
import {loopGraphExplorer,insertLoopGraphExplorer} from '../lib/loop-graph-explorer.mjs';
import {build} from '../lib/site.mjs';
import {loadPackage,validatePackage,configAt,fingerprints} from '../lib/content.mjs';
import {rasterInfo} from '../lib/social-image.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),slug='loops-inside-graphs';
const previous=['parallel-agent-engineering','keeping-parallel-development-fast','better-context-for-ai-agents','jev-decision-layer'];
async function fixture(t){const d=await mkdtemp(path.join(tmpdir(),'loops-graphs-'));t.after(()=>rm(d,{recursive:true,force:true}));for(const n of ['articles','site','lib','studio.config.json'])await cp(path.join(root,n),path.join(d,n),{recursive:true});for(const n of await readdir(path.join(d,'articles')))if(![...previous,slug].includes(n))await rm(path.join(d,'articles',n),{recursive:true,force:true});return d;}
async function status(d,id,value){const p=path.join(d,'articles',id,'metadata.json');const m=JSON.parse(await readFile(p,'utf8'));m.status=value;await writeFile(p,JSON.stringify(m));}
test('all authored traces terminate and only success and repair reach a candidate',()=>{for(const c of scenarios){const xs=traceFor(c.id);assert.ok(xs.length<12);assert.equal(view(xs.at(-1)).releaseReady,['success','repair'].includes(c.id));}});
test('API local repair preserves the passed client candidate and its attempt',()=>{const xs=traceFor('repair');assert.equal(xs[4].api.status,'repair');assert.equal(xs[5].client.attempt,1);assert.equal(xs[5].client.status,'passed');assert.equal(xs[5].api.attempt,2);assert.equal(view(xs.at(-1)).releaseReady,true);});
test('retry exhaustion escalates without integration, approval, or release',()=>{const s=traceFor('exhausted').at(-1);assert.equal(s.api.status,'escalated');assert.equal(s.client.status,'passed');assert.equal(s.integration,null);assert.equal(s.approval,null);assert.equal(s.released,false);assert.throws(()=>transition(s,{kind:'start',lane:'api'}));});
test('contract revision invalidates the old join rather than relabeling evidence',()=>{const s=traceFor('changed').at(-1);assert.equal(s.contract,'r2');assert.equal(s.client.revision,'r1');assert.equal(s.api.status,'stale');assert.equal(canJoin(s),false);assert.throws(()=>transition(s,{kind:'integrate'}));});
test('passed integration alone cannot pass the approval gate',()=>{const s=traceFor('approval').at(-1);assert.equal(view(s).integrated,true);assert.equal(view(s).approved,false);assert.throws(()=>transition(s,{kind:'release'}));});
test('a later contract change clears earlier integration and approval evidence',()=>{const old=traceFor('success').at(-1),s=transition(old,{kind:'contract',revision:'r2',reason:'Changed'});assert.equal(s.integration,null);assert.equal(s.approval,null);assert.equal(s.released,false);assert.equal(old.released,true);});
test('unknown transitions and premature results fail explicitly',()=>{assert.throws(()=>traceFor('unknown'));assert.throws(()=>transition(initialState(),{kind:'pass',lane:'api'}));assert.throws(()=>transition(initialState(),{kind:'start',lane:'other'}));assert.throws(()=>transition(initialState(),{kind:'approve'}));assert.throws(()=>transition(initialState(),{kind:'unknown'}));});
test('static illustration contains a useful repair state with disabled controls',()=>{const h=loopGraphExplorer();assert.match(h,/Authored illustration only/);assert.match(h,/data-status="repair"/);assert.match(h,/data-status="passed"/);assert.match(h,/<fieldset class="lg-controls" disabled/);assert.match(h,/<noscript>/);assert.throws(()=>insertLoopGraphExplorer('missing'));});
test('article distinguishes primary attribution and an unavailable social discovery link',async()=>{const p=await loadPackage(root,slug);assert.deepEqual(await validatePackage(p,await configAt(root)),[]);assert.equal(p.sources.filter(x=>x.type==='primary').length,12);assert.equal(p.sources.filter(x=>x.type==='unverified-link').length,1);assert.match(p.article,/not a newly verified Andrew Ng PDF/);assert.match(p.article,/no live multi-agent benchmark/);const b=await readFile(path.join(p.dir,p.meta.socialImage.path));assert.deepEqual(rasterInfo(b),{type:'image/png',width:1200,height:627});});
test('five-article build features the new article and keeps old pages and feeds',async t=>{const d=await fixture(t),m=await build(d);assert.equal(m.articles.length,5);assert.equal(m.articles[0].slug,slug);const h=await readFile(path.join(d,'dist/articles',slug,'index.html'),'utf8');assert.match(h,/id="loop-graph-explorer"/);assert.match(h,/og:image:width" content="1200"/);assert.ok(!h.includes('src="/content/jev-explorer.js"'));assert.ok(!h.includes('DriftGate'));for(const id of [...previous,slug])for(const f of ['index.html','rss.xml','sitemap.xml'])assert.ok((await readFile(path.join(d,'dist',f),'utf8')).includes('/articles/'+id+'/'));assert.ok(!(await readFile(path.join(d,'dist/index.html'),'utf8')).includes('src="/content/loop-graph-explorer.js"'));});
test('article is independently publishable and removal cleans its modules and image',async t=>{const d=await fixture(t);for(const id of previous)await status(d,id,'review');const m=await build(d);assert.deepEqual(m.articles.map(x=>x.slug),[slug]);assert.ok(m.outputs.includes('loop-graph-model.js'));assert.ok(!m.outputs.includes('jev-model.js'));await status(d,slug,'review');const next=await build(d);assert.ok(!next.outputs.some(x=>x.includes(slug)||x.startsWith('loop-graph-')));});
test('only this article renderer depends on its teaching model',async t=>{const d=await fixture(t),p=await loadPackage(d,slug),o=await loadPackage(d,previous[0]),a=await fingerprints(p,d),b=await fingerprints(o,d),f=path.join(d,'site/loop-graph-model.js');await writeFile(f,(await readFile(f,'utf8'))+'\n// edit fixture\n');assert.notEqual((await fingerprints(p,d)).renderer,a.renderer);assert.equal((await fingerprints(o,d)).renderer,b.renderer);});
